# Generated by Django 2.0.7 on 2019-10-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='score',
        ),
        migrations.AddField(
            model_name='student',
            name='technical_skills_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='verbal_skills_score',
            field=models.IntegerField(default=0),
        ),
    ]
