# Generated by Django 2.0.7 on 2019-10-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191010_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('students', models.ManyToManyField(blank=True, null=True, related_name='students', to='core.Student')),
            ],
        ),
    ]
