# Generated by Django 2.0.7 on 2019-10-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=300)),
                ('packages_range', models.CharField(max_length=200)),
                ('skills_included', models.ManyToManyField(blank=True, null=True, related_name='company_skills', to='core.Skills')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='percentage_graduation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='percentage_tenth',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='percentage_twelth',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='companies',
            name='student_eligible',
            field=models.ManyToManyField(blank=True, null=True, related_name='eligible', to='core.Student'),
        ),
    ]
