# Generated by Django 2.0.7 on 2019-10-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191010_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='percentage_twelth',
            new_name='percentage_twelfth',
        ),
        migrations.AddField(
            model_name='companies',
            name='graduation_criteria',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='companies',
            name='tenth_criteria',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='companies',
            name='twelfth_criteria',
            field=models.FloatField(default=0),
        ),
    ]
