# Generated by Django 2.0.7 on 2019-10-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191010_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='student_skills', to='core.Skills'),
        ),
    ]
